<?php
/**
 * Gutenverse Home Section 4 content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 4', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-mfyRgU","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"20","left":"20"}}}} -->
			<div class="section-wrapper" data-id="mfyRgU"><script>var topmfyRgU = {"Desktop":{"point":"0","unit":"px"}};var bottommfyRgU = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-mfyRgU layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":100},"elementId":"guten-zDrgvb","background":{"type":"default","image":{"Desktop":{"id":1173,"image":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/StockSnap_HWLNQD65VR.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-zDrgvb"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="zDrgvb"><script>var topzDrgvb = {"Desktop":{"point":"0","unit":"px"}};var bottomzDrgvb = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-vMljAl","space":{"Mobile":{"point":"250","unit":"px"}}} -->
			<div class="guten-element guten-spacer guten-vMljAl"></div>
			<!-- /wp:gutenverse/spacer --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-LeGbin","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"70"}},"Tablet":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-LeGbin"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="LeGbin"><script>var topLeGbin = {"Desktop":{"point":"0","unit":"px"}};var bottomLeGbin = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-GTslbK","color":{"r":25,"g":24,"b":47,"a":1},"typography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"44","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.15"},"Tablet":{"point":"36.8","unit":"px"},"Mobile":{"point":"29.9","unit":"px"}},"spacing":{"Desktop":"0.094"},"transform":"uppercase"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-GTslbK animated guten-element-hide desktop-fadeInRight">We Keep Your Business Safe</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-zrqvdO","textColor":{"r":102,"g":102,"b":102,"a":1},"typography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"},"Mobile":{"point":"13","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"},"Tablet":{"point":"22.1","unit":"px"},"Mobile":{"point":"22.1","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"70"}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
			<div class="guten-element gutenverse-text-editor guten-zrqvdO animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/icon-list {"elementId":"guten-7HTZ8R","spaceBetween":{"Desktop":"5"},"iconColor":{"r":100,"g":90,"b":255,"a":1},"iconColorHover":{"r":100,"g":90,"b":255,"a":1},"iconSize":{"Desktop":"15"},"textColor":{"r":102,"g":102,"b":102,"a":1},"textColorHover":{"r":102,"g":102,"b":102,"a":1},"textIndent":{"Desktop":"13","Tablet":"13"},"textTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"},"Mobile":{"point":"13","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"21","unit":"px"},"Tablet":{"point":"19.5","unit":"px"},"Mobile":{"point":"19","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"}} -->
			<div class="guten-element guten-icon-list guten-7HTZ8R animated guten-element-hide desktop-fadeInRight"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-Bridyn"} -->
			<div class="guten-element guten-icon-list-item guten-Bridyn"><a id="guten-Bridyn"><i class="fas fa-check"></i><span class="list-text ">We Help To Create Visual Strategies</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->

			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-vFlp9X"} -->
			<div class="guten-element guten-icon-list-item guten-vFlp9X"><a id="guten-vFlp9X"><i class="fas fa-check"></i><span class="list-text ">We Help To Business Growing Up</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->

			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-p65XnL"} -->
			<div class="guten-element guten-icon-list-item guten-p65XnL"><a id="guten-p65XnL"><i class="fas fa-check"></i><span class="list-text ">We Provide World Class Coaches</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list -->

			<!-- wp:gutenverse/buttons {"elementId":"guten-n7khto"} -->
			<div class="guten-element guten-buttons horizontal guten-n7khto"><!-- wp:gutenverse/button {"elementId":"guten-pByqJi","content":"get a quote","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Tablet":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}}},"buttonBackground":{"type":"default","color":{"r":100,"g":90,"b":255,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":78,"g":69,"b":217,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"r":100,"g":90,"b":255,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"r":78,"g":69,"b":217,"a":1}}},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"15"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"weight":"400","transform":"uppercase","spacing":{"Desktop":"0.094"},"lineHeight":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"13","unit":"px"}}},"hoverTextColor":{"r":255,"g":255,"b":255,"a":1},"positioningType":{"Desktop":"inline"}} -->
			<div class="guten-element guten-button-wrapper guten-pByqJi"><a class="guten-button animated guten-element-hide desktop-fadeInRight guten-button-sm" href="#"><span>get a quote</span></a></div>
			<!-- /wp:gutenverse/button -->

			<!-- wp:gutenverse/button {"elementId":"guten-nFESgU","content":"Learn More","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"25","bottom":"15","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","left":"27","right":"27"}}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"r":100,"g":90,"b":255,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"r":100,"g":90,"b":255,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{}},"all":{"type":"solid","width":"1","color":{"r":100,"g":90,"b":255,"a":1}}},"border":{"radius":{"Desktop":{}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"slow","delay":"800"},"color":{"r":100,"g":90,"b":255,"a":1},"typography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"weight":"400","transform":"uppercase","spacing":{"Desktop":"0.094"},"lineHeight":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"13","unit":"px"}}},"hoverTextColor":{"r":255,"g":255,"b":255,"a":1},"positioningType":{"Desktop":"inline"}} -->
			<div class="guten-element guten-button-wrapper guten-nFESgU"><a class="guten-button animated guten-element-hide slow desktop-fadeInRight guten-button-sm" href="#"><span>Learn More</span></a></div>
			<!-- /wp:gutenverse/button --></div>
			<!-- /wp:gutenverse/buttons --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
