<?php
/**
 * Gutenverse Blog Section 1 content.
 */
return array(
	'title'      => __( 'Gutenverse Blog Section 1', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-cQwtHd","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","bottom":"80"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"0"}}}} -->
			<div class="section-wrapper" data-id="cQwtHd"><script>var topcQwtHd = {"Desktop":{"point":"0","unit":"px"}};var bottomcQwtHd = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-cQwtHd layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-cNIoNK","animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-cNIoNK"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="cNIoNK"><script>var topcNIoNK = {"Desktop":{"point":"0","unit":"px"}};var bottomcNIoNK = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/post-block {"elementId":"guten-rJm8ZW","numberPost":"4","column":{"Desktop":"1"},"categoryEnabled":false,"readmoreIcon":"","commentEnabled":false,"metaAuthorEnabled":false,"postItemMargin":{"Tablet":{}},"postItemPadding":{"Tablet":{}},"postItemBorder":{"radius":{"Tablet":{}}},"thumbnailMargin":{"Desktop":{},"Tablet":{}},"thumbnailPadding":{"Desktop":{},"Tablet":{}},"thumbnailBorder":{"radius":{"Desktop":{},"Tablet":{}}},"contentMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}},"Tablet":{"unit":"px","dimension":{"left":"0"}},"Mobile":{}},"contentPadding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"left":"0"}},"Mobile":{}},"contentBorder":{"radius":{"Desktop":{},"Tablet":{}}},"categoryMargin":{"Tablet":{}},"categoryPadding":{"Tablet":{}},"categoryBorder":{"radius":{"Tablet":{}}},"titleMargin":{"Desktop":{},"Tablet":{}},"titleColor":{"r":18,"g":18,"b":34,"a":1},"titleTypography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"40","unit":"px"},"Tablet":{"point":"38","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"600","lineHeight":{"Mobile":{"point":"28","unit":"px"},"Tablet":{"point":"42","unit":"px"}}},"excerptMargin":{"Desktop":{}},"excerptColor":{"r":102,"g":102,"b":102,"a":1},"excerptTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"readmoreTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.094"}},"readmoreMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"readmorePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"readmoreColor":{"r":100,"g":90,"b":255,"a":1},"readmoreHoverColor":{"r":78,"g":69,"b":217,"a":1},"readmoreBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"readmoreHoverBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"readmoreBorder":{"radius":{"Desktop":{}}},"readmoreHoverBorder":{"radius":{"Desktop":{}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
			<div class="guten-element guten-post-block guten-rJm8ZW"></div>
			<!-- /wp:gutenverse/post-block --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
