<?php
/**
 * Gutenverse content.
 */
return array(
	'title'      => __( 'Gutenverse', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-xbSNFk","border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"140","bottom":"140"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"20","left":"20"}}}} -->
			<div class="section-wrapper" data-id="xbSNFk"><script>var topxbSNFk = {"Desktop":{"point":"0","unit":"px"}};var bottomxbSNFk = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-xbSNFk layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-5VxRFd","background":{"type":"default","image":{"Desktop":{"id":1144,"image":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/StockSnap_LK46EHFEEF.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-5VxRFd animated guten-element-hide desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="5VxRFd"><script>var top5VxRFd = {"Desktop":{"point":"0","unit":"px"}};var bottom5VxRFd = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-j2w1pg","space":{"Desktop":{"unit":"vh","point":"70"},"Tablet":{"point":"364","unit":"px"}}} -->
			<div class="guten-element guten-spacer guten-j2w1pg"></div>
			<!-- /wp:gutenverse/spacer --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-SguYJS","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"70"}},"Tablet":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-SguYJS"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="SguYJS"><script>var topSguYJS = {"Desktop":{"point":"0","unit":"px"}};var bottomSguYJS = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-IBGWfC","color":{"r":18,"g":18,"b":34,"a":1},"typography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"42","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"55.2","unit":"px"},"Tablet":{"point":"36.8","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.094","Mobile":"0.02"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-IBGWfC animated guten-element-hide desktop-fadeInRight">We Provide The Best Solutions To Grow Your Business</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-8ITkKC","textColor":{"r":102,"g":102,"b":102,"a":1},"typography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"},"Mobile":{"point":"13","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"},"Tablet":{"point":"22.1","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40"}},"Tablet":{"unit":"px","dimension":{"right":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"}} -->
			<div class="guten-element gutenverse-text-editor guten-8ITkKC animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-fj02cB","background":{"type":"default","color":{"r":249,"g":249,"b":249,"a":1}},"border":{"radius":{"Desktop":{}},"left":{"type":"solid","color":{"r":78,"g":69,"b":217,"a":1},"width":"7"}},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"}} -->
			<div class="section-wrapper" data-id="fj02cB"><script>var topfj02cB = {"Desktop":{"point":"0","unit":"px"}};var bottomfj02cB = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-fj02cB animated guten-element-hide desktop-fadeInRight layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-a2wMqJ"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-a2wMqJ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="a2wMqJ"><script>var topa2wMqJ = {"Desktop":{"point":"0","unit":"px"}};var bottoma2wMqJ = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-4JGitp","textColor":{"r":102,"g":102,"b":102,"a":1},"typography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"22","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.35"},"Tablet":{"point":"29.7","unit":"px"},"Mobile":{"point":"22","unit":"px"}},"style":"italic"}} -->
			<div class="guten-element gutenverse-text-editor guten-4JGitp"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore incididunt ut labore magna aliqua. </p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
