<?php
/**
 * Gutenverse Home Section 5 content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 5', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1170"},"gap":"no","elementId":"guten-6v2y9Y","background":{"type":"default","color":{"r":243,"g":243,"b":243,"a":1}},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}}}} -->
			<div class="section-wrapper" data-id="6v2y9Y"><script>var top6v2y9Y = {"Desktop":{"point":"0","unit":"px"}};var bottom6v2y9Y = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-6v2y9Y layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"elementId":"guten-y5W8b4","order":{"Mobile":2},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"80","top":"82","right":"70","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"left":"20","right":"20","top":"60","bottom":"60"}},"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"40","right":"20","left":"20"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-y5W8b4"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="y5W8b4"><script>var topy5W8b4 = {"Desktop":{"point":"0","unit":"px"}};var bottomy5W8b4 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-Ca8LBk"} -->
			<div class="section-wrapper" data-id="Ca8LBk"><script>var topCa8LBk = {"Desktop":{"point":"0","unit":"px"}};var bottomCa8LBk = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-Ca8LBk layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-OnqBc0","horizontalAlign":{"Desktop":"flex-end"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-OnqBc0"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="OnqBc0"><script>var topOnqBc0 = {"Desktop":{"point":"0","unit":"px"}};var bottomOnqBc0 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-OH2B7B","color":{"r":25,"g":24,"b":47,"a":1},"typography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"44","unit":"px"},"Tablet":{"point":"30","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.15"},"Tablet":{"point":"36.8","unit":"px"},"Mobile":{"point":"29.9","unit":"px"}},"spacing":{"Desktop":"0.063"},"transform":"uppercase"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInLeft"}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"515","unit":"px"}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-OH2B7B animated guten-element-hide desktop-fadeInLeft">Best Solutions To HELPS YOUR BUSINESS</h2>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-SYapx9"} -->
			<div class="section-wrapper" data-id="SYapx9"><script>var topSYapx9 = {"Desktop":{"point":"0","unit":"px"}};var bottomSYapx9 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-SYapx9 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-7vDfTP","horizontalAlign":{"Desktop":"flex-end"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-7vDfTP"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="7vDfTP"><script>var top7vDfTP = {"Desktop":{"point":"0","unit":"px"}};var bottom7vDfTP = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-E5DiTJ","textColor":{"r":102,"g":102,"b":102,"a":1},"typography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"},"Mobile":{"point":"13","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"},"Tablet":{"point":"22.1","unit":"px"},"Mobile":{"point":"22.1","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"515","unit":"px"}}} -->
			<div class="guten-element gutenverse-text-editor guten-E5DiTJ animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-yNS9Ex"} -->
			<div class="section-wrapper" data-id="yNS9Ex"><script>var topyNS9Ex = {"Desktop":{"point":"0","unit":"px"}};var bottomyNS9Ex = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-yNS9Ex layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-I4FqHk","horizontalAlign":{"Desktop":"flex-end"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-I4FqHk"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="I4FqHk"><script>var topI4FqHk = {"Desktop":{"point":"0","unit":"px"}};var bottomI4FqHk = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-list {"elementId":"guten-hStkEJ","spaceBetween":{"Desktop":"5"},"iconColor":{"r":100,"g":90,"b":255,"a":1},"iconColorHover":{"r":100,"g":90,"b":255,"a":1},"iconSize":{"Desktop":"15"},"textColor":{"r":102,"g":102,"b":102,"a":1},"textColorHover":{"r":102,"g":102,"b":102,"a":1},"textIndent":{"Desktop":"13","Tablet":"13","Mobile":"13"},"textTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"},"Mobile":{"point":"13","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"21","unit":"px"},"Tablet":{"point":"19.1","unit":"px"},"Mobile":{"point":"19.5","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"35"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"515","unit":"px"}}} -->
			<div class="guten-element guten-icon-list guten-hStkEJ animated guten-element-hide desktop-fadeInLeft"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-tvfFZE"} -->
			<div class="guten-element guten-icon-list-item guten-tvfFZE"><a id="guten-tvfFZE"><i class="fas fa-check"></i><span class="list-text ">We Are Leading in Consulting Services</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->

			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-pXjwjQ"} -->
			<div class="guten-element guten-icon-list-item guten-pXjwjQ"><a id="guten-pXjwjQ"><i class="fas fa-check"></i><span class="list-text ">Solutions For Small &amp; Large Business</span></a></div>
			<!-- /wp:gutenverse/icon-list-item -->

			<!-- wp:gutenverse/icon-list-item {"elementId":"guten-ylzVvk"} -->
			<div class="guten-element guten-icon-list-item guten-ylzVvk"><a id="guten-ylzVvk"><i class="fas fa-check"></i><span class="list-text ">Guidence From Our Expert Team</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-NxdNlf"} -->
			<div class="section-wrapper" data-id="NxdNlf"><script>var topNxdNlf = {"Desktop":{"point":"0","unit":"px"}};var bottomNxdNlf = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-NxdNlf layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-3O5jtx","horizontalAlign":{"Desktop":"flex-end"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-3O5jtx"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="3O5jtx"><script>var top3O5jtx = {"Desktop":{"point":"0","unit":"px"}};var bottom3O5jtx = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-VneMQi","content":"GET IT TOUCH","buttonWidth":{"Desktop":"40","Tablet":"55","Mobile":"67"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"25","bottom":"15","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"30","bottom":"15","left":"30"}}},"buttonBackground":{"type":"default","color":{"r":100,"g":90,"b":255,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":78,"g":69,"b":217,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"showIcon":true,"icon":"far fa-envelope","iconSpacing":{"Desktop":"14"},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"border":{"radius":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"600"},"color":{"r":255,"g":255,"b":255,"a":1},"iconColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.063"},"lineHeight":{"Tablet":{"point":"13","unit":"px"}}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"515","unit":"px"}}} -->
			<div class="guten-element guten-button-wrapper guten-VneMQi"><a class="guten-button animated guten-element-hide desktop-fadeInLeft guten-button-sm" href="#"><i class="fa-lg far fa-envelope"></i><span>GET IT TOUCH</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-ZmcB8z","order":{"Mobile":1},"background":{"type":"default","image":{"Desktop":{"id":1178,"image":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/StockSnap_7BQNRHB6EX.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-ZmcB8z"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="ZmcB8z"><script>var topZmcB8z = {"Desktop":{"point":"0","unit":"px"}};var bottomZmcB8z = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-37ipjz","space":{"Mobile":{"point":"250","unit":"px"}}} -->
			<div class="guten-element guten-spacer guten-37ipjz"></div>
			<!-- /wp:gutenverse/spacer --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
