<?php
/**
 * Gutenverse Services Section 3 content.
 */
return array(
	'title'      => __( 'Gutenverse Services Section 3', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-6ldy6n","background":{"type":"default","image":{"Desktop":{"id":1103,"image":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/StockSnap_NHW7CBJDFM.webp"},"Tablet":{"id":476,"image":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/after-work-american-bar-beard-bearded-blond-1450673-pxhere.com.webp"},"Mobile":{"id":476,"image":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/after-work-american-bar-beard-bearded-blond-1450673-pxhere.com.webp"}},"position":{"Desktop":"top center","Tablet":"center center","Mobile":"center center"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat","Mobile":"no-repeat"},"size":{"Desktop":"cover","Tablet":"cover","Mobile":"cover"},"yposition":{"Desktop":{"unit":"px","point":"1"}},"xposition":{"Desktop":{"point":"1","unit":"px"}}},"backgroundOverlay":{"type":"default","color":{"r":36,"g":34,"b":65,"a":1},"gradientColor":[{"color":"rgba(126, 32, 207, 0)","active":false,"opacity":0,"id":2,"offset":"0.000"},{"color":"rgba(31, 39, 50, 1)","opacity":1,"active":true,"id":1,"offset":"0.600"}],"gradientType":"linear","gradientAngle":"90"},"opacity":"0.8","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"110","bottom":"110"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"30","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"20","left":"20"}}}} -->
			<div class="section-wrapper" data-id="6ldy6n"><script>var top6ldy6n = {"Desktop":{"point":"0","unit":"px"}};var bottom6ldy6n = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-6ldy6n layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-77UIDk","verticalAlign":{"Desktop":"center"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-77UIDk"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="77UIDk"><script>var top77UIDk = {"Desktop":{"point":"0","unit":"px"}};var bottom77UIDk = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-mrEHYt","margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-mrEHYt"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="mrEHYt"><script>var topmrEHYt = {"Desktop":{"point":"0","unit":"px"}};var bottommrEHYt = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-1f3peN","color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"42","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"400","transform":"uppercase","lineHeight":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"38.4","unit":"px"},"Mobile":{"point":"31.2","unit":"px"}},"spacing":{"Desktop":"0.094"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInRight"}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-1f3peN animated guten-element-hide desktop-fadeInRight">Best consultations with the best results</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/progress-bar {"elementId":"guten-oE1XXF","style":"tooltip-box","title":"Industry Business","percentage":"80","duration":"3000","barColor":{"r":255,"g":255,"b":255,"a":1},"trackColor":{"r":78,"g":69,"b":217,"a":1},"trackHeight":{"Desktop":"15"},"barRadius":{"Desktop":{}},"trackRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"barPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"barMargin":{"Desktop":{}},"titleColor":{"r":255,"g":255,"b":255,"a":1},"titleTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"transform":"uppercase","lineHeight":{"Desktop":{"unit":"em","point":"2.9"}},"spacing":{"Desktop":"0.088"},"weight":"400"},"percentColor":{"r":78,"g":69,"b":217,"a":1},"percentTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"11","unit":"px"}}},"percentBgColor":{"r":255,"g":255,"b":255,"a":1}} -->
			<div class="guten-element guten-progress-bar guten-oE1XXF"><div class="progress-group tooltip-box"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">Industry Business</span></div><div class="skill-bar"><div class="skill-track" data-width="80" data-duration="3000"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
			<!-- /wp:gutenverse/progress-bar -->

			<!-- wp:gutenverse/progress-bar {"elementId":"guten-uttt11","style":"tooltip-box","title":"Online Business","percentage":"85","duration":"3000","barColor":{"r":255,"g":255,"b":255,"a":1},"trackColor":{"r":78,"g":69,"b":217,"a":1},"trackHeight":{"Desktop":"15"},"barRadius":{"Desktop":{}},"trackRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"barPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"barMargin":{"Desktop":{}},"titleColor":{"r":255,"g":255,"b":255,"a":1},"titleTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"transform":"uppercase","lineHeight":{"Desktop":{"unit":"em","point":"2.9"}},"spacing":{"Desktop":"0.088"},"weight":"400"},"percentColor":{"r":78,"g":69,"b":217,"a":1},"percentTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"11","unit":"px"}}},"percentBgColor":{"r":255,"g":255,"b":255,"a":1}} -->
			<div class="guten-element guten-progress-bar guten-uttt11"><div class="progress-group tooltip-box"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">Online Business</span></div><div class="skill-bar"><div class="skill-track" data-width="85" data-duration="3000"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
			<!-- /wp:gutenverse/progress-bar -->

			<!-- wp:gutenverse/progress-bar {"elementId":"guten-FKeesZ","style":"tooltip-box","title":"Property Business","percentage":"67","duration":"3000","barColor":{"r":255,"g":255,"b":255,"a":1},"trackColor":{"r":78,"g":69,"b":217,"a":1},"trackHeight":{"Desktop":"15"},"barRadius":{"Desktop":{}},"trackRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"barPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"barMargin":{"Desktop":{}},"titleColor":{"r":255,"g":255,"b":255,"a":1},"titleTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"transform":"uppercase","lineHeight":{"Desktop":{"unit":"em","point":"2.9"}},"spacing":{"Desktop":"0.088"},"weight":"400"},"percentColor":{"r":78,"g":69,"b":217,"a":1},"percentTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"11","unit":"px"}}},"percentBgColor":{"r":255,"g":255,"b":255,"a":1}} -->
			<div class="guten-element guten-progress-bar guten-FKeesZ"><div class="progress-group tooltip-box"><div class="progress-skill-bar"><div class="skill-bar-content"><span class="skill-title">Property Business</span></div><div class="skill-bar"><div class="skill-track" data-width="67" data-duration="3000"><div class="number-percentage-wrapper"><span class="number-percentage loaded"></span></div></div></div></div></div></div>
			<!-- /wp:gutenverse/progress-bar --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
