<?php
/**
 * Gutenverse Home Section 1 content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 1', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-YHzNpD","background":{"type":"default","color":{"r":25,"g":24,"b":47,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}}}} -->
			<div class="section-wrapper" data-id="YHzNpD"><script>var topYHzNpD = {"Desktop":{"point":"0","unit":"px"}};var bottomYHzNpD = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-YHzNpD layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-8lAHDh"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-8lAHDh"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="8lAHDh"><script>var top8lAHDh = {"Desktop":{"point":"0","unit":"px"}};var bottom8lAHDh = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-1CPcdF","verticalAlign":"center","background":{"type":"default","color":{"r":36,"g":34,"b":65,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-60"}},"Tablet":{"unit":"px","dimension":{"top":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}} -->
			<div class="section-wrapper" data-id="1CPcdF"><script>var top1CPcdF = {"Desktop":{"point":"0","unit":"px"}};var bottom1CPcdF = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-1CPcdF layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":66.66,"Tablet":null,"Mobile":100},"elementId":"guten-rFt33O","verticalAlign":{"Desktop":"center","Tablet":"center"},"margin":{"Mobile":{}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"animation":{"type":{"Desktop":"fadeInUp"}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-rFt33O animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="rFt33O"><script>var toprFt33O = {"Desktop":{"point":"0","unit":"px"}};var bottomrFt33O = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-cLuwxc","type":4,"textAlign":{"Mobile":"center"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"500","lineHeight":{"Mobile":{"point":"36","unit":"px"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"slow"}} -->
			<h4 class="wp-block-gutenverse-heading guten-element guten-cLuwxc animated guten-element-hide slow desktop-fadeInUp">Needs Experience Business Consultant?</h4>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":100},"elementId":"guten-1wMNqH","verticalAlign":{"Desktop":"center"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-1wMNqH"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="1wMNqH"><script>var top1wMNqH = {"Desktop":{"point":"0","unit":"px"}};var bottom1wMNqH = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-yBBmsA","content":"Contact Us","alignButton":{"Desktop":"right","Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}},"Tablet":{},"Mobile":{}},"buttonBackground":{"type":"default","color":{"r":100,"g":90,"b":255,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":78,"g":69,"b":217,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"showIcon":true,"icon":"far fa-envelope","iconSpacing":{"Desktop":"14"},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"margin":{"Mobile":{}},"padding":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"slow"},"color":{"r":252,"g":252,"b":252,"a":1},"iconColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"14","unit":"px"}},"spacing":{"Desktop":"0.0625"},"transform":"uppercase"}} -->
			<div class="guten-element guten-button-wrapper guten-yBBmsA"><a class="guten-button animated guten-element-hide slow desktop-fadeInUp guten-button-sm" href="#"><i class="fa-lg far fa-envelope"></i><span>Contact Us</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/section {"width":{"Desktop":"1170","Tablet":"1170"},"isChild":true,"gap":"no","elementId":"guten-34Ghnb","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-100"}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"9","right":"16","bottom":"","left":"16"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"50","bottom":"50"}},"Mobile":{"unit":"px","dimension":{"top":"40"}}}} -->
			<div class="section-wrapper" data-id="34Ghnb"><script>var top34Ghnb = {"Desktop":{"point":"0","unit":"px"}};var bottom34Ghnb = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-34Ghnb layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-rurxUU","margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-rurxUU"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="rurxUU"><script>var toprurxUU = {"Desktop":{"point":"0","unit":"px"}};var bottomrurxUU = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-HVR9yr","type":6,"textAlign":{"Desktop":"center"},"color":{"r":100,"g":90,"b":255,"a":1},"typography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","transform":"uppercase","spacing":{"Desktop":"0.0625"}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-HVR9yr animated guten-element-hide desktop-fadeInUp">Why Choose Us</h6>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/heading {"elementId":"guten-LoJ4UT","textAlign":{"Desktop":"center"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"size":{"Desktop":{"point":"44","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"400","font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"transform":"uppercase","lineHeight":{"Desktop":{"unit":"em","point":"1.3"},"Tablet":{"point":"41.6","unit":"px"},"Mobile":{"point":"33.8","unit":"px"}},"spacing":{"Desktop":"0.0625"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"60"}},"Mobile":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-LoJ4UT animated guten-element-hide desktop-fadeInUp">We Keep Your Business Safe &amp; Ensure High Availability</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"elementId":"guten-CxZf7g","background":{"type":"default","image":{"Desktop":{"id":1083,"image":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/StockSnap_CZVXLM4SH2.webp"}},"position":{"Mobile":"center center","Desktop":"center center"},"repeat":{"Mobile":"no-repeat","Desktop":"no-repeat"},"size":{"Mobile":"cover","Desktop":"cover"}},"backgroundOverlay":{"type":"default","color":{"r":36,"g":34,"b":65,"a":1}},"opacity":"0.3","border":{"radius":{"Desktop":{}}},"boxShadow":{"vertical":"15","blur":"30","color":{"r":0,"g":0,"b":0,"a":0.31}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-30"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"160","bottom":"160"}},"Mobile":{"unit":"px","dimension":{"top":"60","bottom":"60"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"}} -->
			<div class="section-wrapper" data-id="CxZf7g"><script>var topCxZf7g = {"Desktop":{"point":"0","unit":"px"}};var bottomCxZf7g = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-CxZf7g animated guten-element-hide desktop-fadeInUp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-JQ9Xdd","margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-JQ9Xdd"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="JQ9Xdd"><script>var topJQ9Xdd = {"Desktop":{"point":"0","unit":"px"}};var bottomJQ9Xdd = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon {"elementId":"guten-lZNiQD","icon":"fas fa-play","iconAlign":{"Desktop":"center"},"iconColorOne":{"r":0,"g":0,"b":0,"a":0.5},"iconSize":{"Desktop":{"point":"18","unit":"px"}},"iconPadding":{"Desktop":"30"},"iconColorTwo":{"r":255,"g":255,"b":255,"a":1},"iconColorHoverOne":{"r":0,"g":0,"b":0,"a":0.87},"iconColorHoverTwo":{"r":255,"g":255,"b":255,"a":1},"iconShape":"circle","url":"#"} -->
			<div class="wp-block-gutenverse-icon guten-element guten-lZNiQD guten-icon"><a class="guten-icon-wrapper circle stacked" href="#"><i class="fas fa-play"></i></a></div>
			<!-- /wp:gutenverse/icon --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
