<?php
/**
 * Gutenverse Contact Section 1 content.
 */
return array(
	'title'      => __( 'Gutenverse Contact Section 1', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-5kevJW","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"120"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"60","right":"20","left":"20"}}}} -->
			<div class="section-wrapper" data-id="5kevJW"><script>var top5kevJW = {"Desktop":{"point":"0","unit":"px"}};var bottom5kevJW = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-5kevJW layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-KppHJc","margin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"11"}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-KppHJc"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="KppHJc"><script>var topKppHJc = {"Desktop":{"point":"0","unit":"px"}};var bottomKppHJc = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-Kokymp","textAlign":{"Mobile":"center"},"color":{"r":0,"g":0,"b":0,"a":1},"typography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"400","transform":"uppercase","lineHeight":{"Desktop":{"unit":"em","point":"1.15"},"Tablet":{"unit":"em","point":"1.15"}},"spacing":{"Desktop":"0.063"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-Kokymp animated guten-element-hide desktop-fadeInLeft">GENERAL INQUIRIES</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-RUjFLZ","textColor":{"r":102,"g":102,"b":102,"a":1},"typography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"},"Mobile":{"point":"13","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.8"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
			<div class="guten-element gutenverse-text-editor guten-RUjFLZ animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/form-builder {"elementId":"guten-GA669t","formId":{"label":"Form Inquiries","value":231},"redirectTo":"","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
			<form style="display:none" class="guten-element guten-form-builder guten-GA669t animated guten-element-hide desktop-fadeInUp" data-form-id="231" data-redirect=""><!-- wp:gutenverse/form-input-text {"elementId":"guten-eCNt7V","showLabel":false,"inputPlaceholder":"Name","showHelper":false,"border":{"radius":{"Desktop":{}},"all":{"type":"none","width":"1","color":{"r":224,"g":224,"b":224,"a":1}}},"borderHover":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"8","bottom":"8","right":"16","left":"16"}}},"inputMargin":{"Desktop":{}},"placeholderColor":{"Desktop":{"r":135,"g":137,"b":138,"a":1}},"inputTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}}},"inputColorNormal":{"Desktop":{"r":0,"g":0,"b":0,"a":1}},"inputBorderNormal":{"radius":{"Desktop":{}}},"inputColorHover":{"Desktop":{"r":0,"g":0,"b":0,"a":1}},"inputBorderHover":{"radius":{"Desktop":{}}},"inputColorFocus":{"Desktop":{"r":0,"g":0,"b":0,"a":1}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid"}}} -->
			<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-eCNt7V hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Name" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
			<!-- /wp:gutenverse/form-input-text -->

			<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-ssi1e3","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}}} -->
			<div class="section-wrapper" data-id="ssi1e3"><script>var topssi1e3 = {"Desktop":{"point":"0","unit":"px"}};var bottomssi1e3 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-ssi1e3 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-iIq4Qg","margin":{"Mobile":{"unit":"px","dimension":{"right":"0"}}},"padding":{"Mobile":{"unit":"px","dimension":{"right":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-iIq4Qg"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="iIq4Qg"><script>var topiIq4Qg = {"Desktop":{"point":"0","unit":"px"}};var bottomiIq4Qg = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-email {"elementId":"guten-Ymxpwl","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":{}},"labelMargin":{"Desktop":{}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0","bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"inputPlaceholder":"Email","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"8","bottom":"8","right":"16","left":"16"}}},"inputMargin":{"Desktop":{}},"placeholderColor":{"Desktop":{"r":135,"g":137,"b":138,"a":1}},"inputTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}}},"inputColorNormal":{"Desktop":{"r":0,"g":0,"b":0,"a":1}},"inputBorderNormal":{"radius":{"Desktop":{}}},"inputColorHover":{"Desktop":{"r":0,"g":0,"b":0,"a":1}},"inputBorderHover":{"radius":{"Desktop":{}}},"inputColorFocus":{"Desktop":{"r":0,"g":0,"b":0,"a":1}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid"}}} -->
			<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-Ymxpwl hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Email" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
			<!-- /wp:gutenverse/form-input-email --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-pDHGEC"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-pDHGEC"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="pDHGEC"><script>var toppDHGEC = {"Desktop":{"point":"0","unit":"px"}};var bottompDHGEC = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-telp {"elementId":"guten-X7S4Tb","showLabel":false,"showHelper":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{}},"inputPlaceholder":"Phone","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"8","bottom":"8","right":"16","left":"16"}}},"inputMargin":{"Desktop":{}},"placeholderColor":{"Desktop":{"r":135,"g":137,"b":138,"a":1}},"inputTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}}},"inputColorNormal":{"Desktop":{"r":0,"g":0,"b":0,"a":1}},"inputBorderNormal":{"radius":{"Desktop":{}}},"inputColorHover":{"Desktop":{"r":0,"g":0,"b":0,"a":1}},"inputBorderHover":{"radius":{"Desktop":{}}},"inputColorFocus":{"Desktop":{"r":0,"g":0,"b":0,"a":1}},"inputBorderFocus":{"radius":{"Desktop":{}}}} -->
			<div class="guten-element guten-form-input-telp guten-form-input guten-input-position-top guten-X7S4Tb hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;telp&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Phone" name="input-telp" class="gutenverse-input gutenverse-input-tel" type="tel" pattern="[0-9]{3}-[0-9]{2}-[0-9]{3}"/><div class="validation-error">Input Invalid</div></div></div>
			<!-- /wp:gutenverse/form-input-telp --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/form-input-textarea {"elementId":"guten-Y9CiBk","showLabel":false,"showHelper":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputHeight":{"Desktop":"120"},"inputPlaceholder":"How We Can Help You?","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"8","bottom":"8","right":"16","left":"16"}}},"inputMargin":{"Desktop":{}},"placeholderColor":{"Desktop":{"r":135,"g":137,"b":138,"a":1}},"inputTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}}},"inputColorNormal":{"Desktop":{"r":0,"g":0,"b":0,"a":1}},"inputBorderNormal":{"radius":{"Desktop":{}}},"inputColorHover":{"Desktop":{"r":0,"g":0,"b":0,"a":1}},"inputBorderHover":{"radius":{"Desktop":{}}},"inputColorFocus":{"Desktop":{"r":0,"g":0,"b":0,"a":1}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid"}}} -->
			<div class="guten-element guten-form-input-textarea guten-form-input guten-input-position-top guten-Y9CiBk hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><textarea data-validation="{&quot;type&quot;:&quot;textarea&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="How We Can Help You?" name="input-textarea" class="gutenverse-input gutenverse-input-text"></textarea><div class="validation-error">Input Invalid</div></div></div>
			<!-- /wp:gutenverse/form-input-textarea -->

			<!-- wp:gutenverse/form-input-submit {"elementId":"guten-awe1h4","content":"Submit","buttonBackground":{"type":"default","color":{"r":100,"g":90,"b":255,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":78,"g":69,"b":217,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.063"}},"hoverTextColor":{"r":255,"g":255,"b":255,"a":1},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}},"Tablet":{},"Mobile":{}}} -->
			<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-awe1h4"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Submit</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
			<!-- /wp:gutenverse/form-input-submit --></form>
			<!-- /wp:gutenverse/form-builder --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"elementId":"guten-jx35BF","margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"top":"0"}},"Tablet":{}},"padding":{"Desktop":{"unit":"%","dimension":{"left":"11"}},"Mobile":{"unit":"px","dimension":{"left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"50"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-jx35BF"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="jx35BF"><script>var topjx35BF = {"Desktop":{"point":"0","unit":"px"}};var bottomjx35BF = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-17QwyA","color":{"r":0,"g":0,"b":0,"a":1},"typography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"400","transform":"uppercase","lineHeight":{"Desktop":{"unit":"em","point":"1.15"}},"spacing":{"Desktop":"0.094"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-17QwyA animated guten-element-hide desktop-fadeInRight">Contact Info</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/icon-list {"elementId":"guten-XZynzE","spaceBetween":{"Desktop":"10"},"iconColor":{"r":100,"g":90,"b":255,"a":1},"iconColorHover":{"r":100,"g":90,"b":255,"a":1},"textColor":{"r":102,"g":102,"b":102,"a":1},"textColorHover":{"r":102,"g":102,"b":102,"a":1},"textIndent":{"Desktop":"8","Tablet":"8"},"textTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"21","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":""}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"right":"20"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
			<div class="guten-element guten-icon-list guten-XZynzE animated guten-element-hide desktop-fadeInRight"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-75EEYc","margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
			<div class="guten-element guten-icon-list-item guten-75EEYc"><a id="guten-75EEYc"><i class="fas fa-map-pin"></i><span class="list-text "> 1010 Avenue of the Moon New York, NY 10018 US.</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list -->

			<!-- wp:gutenverse/icon-list {"elementId":"guten-Htuo6U","spaceBetween":{"Desktop":"10"},"iconColor":{"r":100,"g":90,"b":255,"a":1},"iconColorHover":{"r":100,"g":90,"b":255,"a":1},"textColor":{"r":102,"g":102,"b":102,"a":1},"textColorHover":{"r":102,"g":102,"b":102,"a":1},"textIndent":{"Desktop":"8","Tablet":"8"},"textTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"21","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":""}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"right":"20"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"}} -->
			<div class="guten-element guten-icon-list guten-Htuo6U animated guten-element-hide desktop-fadeInRight"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-SuZtIz"} -->
			<div class="guten-element guten-icon-list-item guten-SuZtIz"><a id="guten-SuZtIz"><i class="fas fa-phone-alt"></i><span class="list-text ">+62 628 123 4000</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list -->

			<!-- wp:gutenverse/icon-list {"elementId":"guten-55cgKp","spaceBetween":{"Desktop":"10"},"iconColor":{"r":100,"g":90,"b":255,"a":1},"iconColorHover":{"r":100,"g":90,"b":255,"a":1},"textColor":{"r":102,"g":102,"b":102,"a":1},"textColorHover":{"r":102,"g":102,"b":102,"a":1},"textIndent":{"Desktop":"8","Tablet":"8"},"textTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"21","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":""}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"right":"20"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"}} -->
			<div class="guten-element guten-icon-list guten-55cgKp animated guten-element-hide desktop-fadeInRight"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-8ec7ba"} -->
			<div class="guten-element guten-icon-list-item guten-8ec7ba"><a id="guten-8ec7ba"><i class="fas fa-fax"></i><span class="list-text ">+62 628 123 4001</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list -->

			<!-- wp:gutenverse/icon-list {"elementId":"guten-9flNcd","spaceBetween":{"Desktop":"10"},"iconColor":{"r":100,"g":90,"b":255,"a":1},"iconColorHover":{"r":100,"g":90,"b":255,"a":1},"textColor":{"r":102,"g":102,"b":102,"a":1},"textColorHover":{"r":102,"g":102,"b":102,"a":1},"textIndent":{"Desktop":"8","Tablet":"8"},"textTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"21","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"60"}},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{}},"padding":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"right":"20"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"800"}} -->
			<div class="guten-element guten-icon-list guten-9flNcd animated guten-element-hide desktop-fadeInRight"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-GREviv"} -->
			<div class="guten-element guten-icon-list-item guten-GREviv"><a id="guten-GREviv"><i class="fas fa-envelope"></i><span class="list-text ">contact@yourdomain.com</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list -->

			<!-- wp:gutenverse/heading {"elementId":"guten-S4Kxs1","color":{"r":0,"g":0,"b":0,"a":1},"typography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"400","transform":"uppercase","lineHeight":{"Desktop":{"unit":"px","point":"48"}},"spacing":{"Desktop":"0.094"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{}},"padding":{"Desktop":{},"Tablet":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"1000"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-S4Kxs1 animated guten-element-hide desktop-fadeInRight">Social Media</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-r1zcmu","textColor":{"r":102,"g":102,"b":102,"a":1},"typography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"23.8","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"1200"}} -->
			<div class="guten-element gutenverse-text-editor guten-r1zcmu animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Connect with us via social media.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/social-icons {"elementId":"guten-4IFu0X","iconSize":{"Desktop":{"point":"16","unit":"px"}},"gap":{"Desktop":"10"},"alignment":{"Desktop":"flex-start"},"shape":"circle","itemPadding":{"Desktop":{}}} -->
			<div class="guten-element guten-social-icons guten-4IFu0X circle horizontal fill"><!-- wp:gutenverse/social-icon {"elementId":"guten-Sbnfxf","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":59,"g":89,"b":152,"a":1},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":59,"g":89,"b":152,"a":1},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"1400"}} -->
			<div class="guten-element guten-social-icon guten-Sbnfxf facebook animated guten-element-hide desktop-fadeInUp"><a id="guten-Sbnfxf"><i class="fab fa-facebook"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->

			<!-- wp:gutenverse/social-icon {"elementId":"guten-1k558w","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":29,"g":161,"b":242,"a":1},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":29,"g":161,"b":242,"a":1},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"1600"}} -->
			<div class="guten-element guten-social-icon guten-1k558w twitter animated guten-element-hide desktop-fadeInUp"><a id="guten-1k558w"><i class="fab fa-twitter"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->

			<!-- wp:gutenverse/social-icon {"elementId":"guten-yB8Iuo","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":205,"g":32,"b":31,"a":1},"hoverIconColor":{"r":255,"g":254,"b":254,"a":1},"hoverBgColor":{"r":205,"g":32,"b":31,"a":1},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"1800"}} -->
			<div class="guten-element guten-social-icon guten-yB8Iuo youtube animated guten-element-hide desktop-fadeInUp"><a id="guten-yB8Iuo"><i class="fab fa-youtube"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->

			<!-- wp:gutenverse/social-icon {"elementId":"guten-J7bLbx","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":0,"g":119,"b":181,"a":1},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":0,"g":119,"b":181,"a":1},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"2000"}} -->
			<div class="guten-element guten-social-icon guten-J7bLbx link animated guten-element-hide desktop-fadeInUp"><a id="guten-J7bLbx"><i class="fab fa-linkedin"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->

			<!-- wp:gutenverse/social-icon {"elementId":"guten-RC6ZXq","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":38,"g":38,"b":38,"a":1},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverBgColor":{"r":38,"g":38,"b":38,"a":1},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"2200"}} -->
			<div class="guten-element guten-social-icon guten-RC6ZXq instagram animated guten-element-hide desktop-fadeInUp"><a id="guten-RC6ZXq"><i class="fab fa-instagram"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon --></div>
			<!-- /wp:gutenverse/social-icons --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
