<?php
/**
 * Gutenverse Page Section 1 content.
 */
return array(
	'title'      => __( 'Gutenverse Page Section 1', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-6CCWOZ","background":{"type":"default"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40"}}}} -->
			<div class="section-wrapper" data-id="6CCWOZ"><script>var top6CCWOZ = {"Desktop":{"point":"0","unit":"px"}};var bottom6CCWOZ = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-6CCWOZ layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-NnoNRE","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-NnoNRE"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="NnoNRE"><script>var topNnoNRE = {"Desktop":{"point":"0","unit":"px"}};var bottomNnoNRE = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/post-content {"elementId":"guten-846Cfv","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40","top":"0"}}},"padding":{"Desktop":{}}} -->
			<div class="guten-element guten-post-content guten-846Cfv"></div>
			<!-- /wp:gutenverse/post-content -->
			
			<!-- wp:gutenverse/post-comment {"elementId":"guten-XbWBEP","typographyHeading":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"28","unit":"px"}},"lineHeight":{"Desktop":{"point":"40","unit":"px"}},"weight":"800"},"typographyText":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"}},"weight":"400"},"typographyLink":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"22.5","unit":"px"}},"weight":"400"},"typographyLabel":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"50","unit":"px"}},"weight":"400"},"colorHeading":{"r":18,"g":18,"b":34,"a":1},"colorText":{"r":18,"g":18,"b":34,"a":1},"colorLink":{"r":100,"g":90,"b":255,"a":1},"colorLabel":{"r":18,"g":18,"b":34,"a":1},"inputBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"r":234,"g":234,"b":239,"a":1}}},"typographyButton":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"28","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.0625"}},"colorButton":{"r":255,"g":255,"b":255,"a":1},"bgcolorButton":{"r":100,"g":90,"b":255,"a":1},"borderButton":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"colorButtonHover":{"r":255,"g":255,"b":255,"a":1},"bgcolorButtonHover":{"r":78,"g":69,"b":217,"a":1},"borderButtonHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
			<div class="guten-element guten-post-comment guten-XbWBEP"></div>
			<!-- /wp:gutenverse/post-comment --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
