<?php
/**
 * Gutenverse Home Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Home Hero', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-Lf5oR1","background":{"type":"default","image":{"Desktop":{"id":1007,"image":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/StockSnap_SZCQC1QEW1.webp"},"Tablet":{"id":1007,"image":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/StockSnap_SZCQC1QEW1.webp"},"Mobile":{"id":1156,"image":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/mobile-StockSnap_SZCQC1QEW1.webp"}},"position":{"Desktop":"center right","Tablet":"center center","Mobile":"center center"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat","Mobile":"no-repeat"},"size":{"Desktop":"cover","Tablet":"cover","Mobile":"cover"},"width":{"Desktop":{"unit":"%","point":"100"},"Tablet":{"unit":"%","point":"100"}}},"backgroundOverlay":{"type":"gradient","gradientType":"linear","gradientColor":[{"color":"rgba(18, 18, 34, 1)","active":false,"opacity":1,"id":1,"offset":"0.388"},{"color":"rgba(53, 32, 207, 0)","active":true,"opacity":0,"id":2,"offset":"0.391"}],"gradientAngle":"90"},"opacity":"","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"220","bottom":"260"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"20","left":"20"}}}} -->
			<div class="section-wrapper" data-id="Lf5oR1"><script>var topLf5oR1 = {"Desktop":{"point":"0","unit":"px"}};var bottomLf5oR1 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-Lf5oR1 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null,"Tablet":null},"elementId":"guten-UVG1ok","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{},"Tablet":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"350","top":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"200"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-UVG1ok"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="UVG1ok"><script>var topUVG1ok = {"Desktop":{"point":"0","unit":"px"}};var bottomUVG1ok = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-VKGFxI","type":6,"color":{"r":100,"g":90,"b":255,"a":1},"typography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"500","lineHeight":{"Desktop":{"point":"18","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"spacing":{"Desktop":"0.0625"},"transform":"uppercase"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":""}} -->
			<h6 class="wp-block-gutenverse-heading guten-element guten-VKGFxI animated guten-element-hide desktop-fadeInLeft">Since 2006</h6>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/heading {"elementId":"guten-PZ46kp","color":{"r":252,"g":252,"b":252,"a":1},"typography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"80","unit":"px"},"Tablet":{"point":"50","unit":"px"},"Mobile":{"point":"30","unit":"px"}},"lineHeight":{"Desktop":{"point":"96","unit":"px"},"Tablet":{"unit":"em","point":"1.2"},"Mobile":{"point":"42","unit":"px"}},"weight":"500"},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"30","left":""}},"Mobile":{"unit":"px","dimension":{"right":"50"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-PZ46kp animated guten-element-hide desktop-fadeInLeft">The Best Solutions To Grow Your Business</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/button {"elementId":"guten-qoOxka","content":"Get started","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"40","left":"40"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"40","left":"40"}}},"buttonBackground":{"type":"default","color":{"r":100,"g":90,"b":255,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":78,"g":69,"b":217,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"buttonBorderHover":{"radius":{"Desktop":{}}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"16"},"iconSize":{"Desktop":{"point":"13","unit":"px"}},"border":{"radius":{"Desktop":{}}},"margin":{"Mobile":{}},"padding":{"Mobile":{"unit":"px","dimension":{"top":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"},"color":{"r":255,"g":255,"b":255,"a":1},"iconColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","lineHeight":{"Desktop":{"point":"14","unit":"px"}},"spacing":{"Desktop":"0.0625"}},"hoverIconColor":{"r":255,"g":255,"b":255,"a":1},"hoverTextColor":{"r":255,"g":255,"b":255,"a":1}} -->
			<div class="guten-element guten-button-wrapper guten-qoOxka"><a class="guten-button animated guten-element-hide desktop-fadeInLeft guten-button-sm" href="#"><span>Get started</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
