<?php
/**
 * Gutenverse Home Section 3 content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 3', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-yIG5li","background":{"type":"default","image":{"Desktop":{"id":1084,"image":"' . esc_url( HYPEBIZ_URI ) . 'assets/img/StockSnap_V8SXASKPBO.webp"}},"position":{"Desktop":"top center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"default","color":{"r":36,"g":34,"b":65,"a":1}},"opacity":"0.7","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"140","bottom":"140"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"60","bottom":"40","right":"20","left":"20"}}}} -->
			<div class="section-wrapper" data-id="yIG5li"><script>var topyIG5li = {"Desktop":{"point":"0","unit":"px"}};var bottomyIG5li = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-yIG5li layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":70,"Mobile":null},"elementId":"guten-H0Lj5x"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-H0Lj5x"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="H0Lj5x"><script>var topH0Lj5x = {"Desktop":{"point":"0","unit":"px"}};var bottomH0Lj5x = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-VUbiU1","color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"44","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"400","transform":"uppercase","lineHeight":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"28.4","unit":"px"},"Mobile":{"point":"31.2","unit":"px"}},"spacing":{"Desktop":""}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"right":"50"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-VUbiU1 animated guten-element-hide desktop-fadeInLeft">YEARS OF EXPERIENCE</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-ChUzil","textColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"},"Mobile":{"point":"13","unit":"px"}},"lineHeight":{"Desktop":{"point":"23.8","unit":"px"},"Tablet":{"point":"22.1","unit":"px"},"Mobile":{"point":"22.1","unit":"px"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"50"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
			<div class="guten-element gutenverse-text-editor guten-ChUzil animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip. </p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-Dnyqdl"} -->
			<div class="section-wrapper" data-id="Dnyqdl"><script>var topDnyqdl = {"Desktop":{"point":"0","unit":"px"}};var bottomDnyqdl = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-Dnyqdl layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Mobile":null},"elementId":"guten-CggyZ0","margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-CggyZ0"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="CggyZ0"><script>var topCggyZ0 = {"Desktop":{"point":"0","unit":"px"}};var bottomCggyZ0 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-wDmGip","iconType":"none","icon":"","iconBorder":{"radius":{"Desktop":{},"Tablet":{}}},"iconPadding":{"Desktop":{},"Tablet":{}},"iconMargin":{"Desktop":{},"Tablet":{}},"prefix":"","number":"927","suffix":"","title":"Happy Clients","numberColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"numberTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"40","unit":"px"},"Tablet":{"point":"32","unit":"px"}},"weight":"500","spacing":{"Desktop":""}},"titleTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"},"Tablet":{"point":"12","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"transform":"uppercase","spacing":{"Desktop":"0.063"}},"numberBottomSpace":{"Desktop":"-10"},"titleBottomSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"20","left":"15"}},"Mobile":{}},"background":{"type":"default","color":{"r":100,"g":90,"b":255,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}},"Mobile":{"unit":"px","dimension":{"right":"0","bottom":"10"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
			<div class="guten-element guten-wDmGip guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="927" data-duration="3500"></span><span class="suffix"></span></div><span class="title">Happy Clients</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Mobile":null},"elementId":"guten-bzdHAZ","margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-bzdHAZ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="bzdHAZ"><script>var topbzdHAZ = {"Desktop":{"point":"0","unit":"px"}};var bottombzdHAZ = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-n8eJ7T","iconType":"none","icon":"","iconBorder":{"radius":{"Desktop":{}}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{}},"prefix":"","number":"72","suffix":"","title":"Team Members","numberColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"numberTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"40","unit":"px"},"Tablet":{"point":"32","unit":"px"}},"weight":"500","spacing":{"Desktop":""}},"titleTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"},"Tablet":{"point":"12","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"transform":"uppercase","spacing":{"Desktop":"0.063"}},"numberBottomSpace":{"Desktop":"-10"},"titleBottomSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"20","left":"15"}},"Mobile":{}},"background":{"type":"default","color":{"r":100,"g":90,"b":255,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","bottom":"10"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
			<div class="guten-element guten-n8eJ7T guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="72" data-duration="3500"></span><span class="suffix"></span></div><span class="title">Team Members</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336},"elementId":"guten-wstJdr","animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-wstJdr"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="wstJdr"><script>var topwstJdr = {"Desktop":{"point":"0","unit":"px"}};var bottomwstJdr = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-3pPI9y","iconType":"none","icon":"","iconBorder":{"radius":{"Desktop":{}}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{}},"prefix":"","number":"94","suffix":"","title":"COUNTRIES","numberColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"titleColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"numberTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"40","unit":"px"},"Tablet":{"point":"32","unit":"px"}},"weight":"500","spacing":{"Desktop":""}},"titleTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"},"Tablet":{"point":"12","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"transform":"uppercase","spacing":{"Desktop":"0.063"}},"numberBottomSpace":{"Desktop":"-10"},"titleBottomSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"20","left":"15"}},"Mobile":{}},"background":{"type":"default","color":{"r":100,"g":90,"b":255,"a":1}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
			<div class="guten-element guten-3pPI9y guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="94" data-duration="3500"></span><span class="suffix"></span></div><span class="title">COUNTRIES</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":25},"elementId":"guten-HlTLo9"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-HlTLo9"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="HlTLo9"><script>var topHlTLo9 = {"Desktop":{"point":"0","unit":"px"}};var bottomHlTLo9 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
