<?php
/**
 * Gutenverse Home Section 8 content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 8', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-SQQyeN","verticalAlign":"center","background":{"type":"default","color":{"r":36,"g":34,"b":65,"a":1}},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}} -->
			<div class="section-wrapper" data-id="SQQyeN"><script>var topSQQyeN = {"Desktop":{"point":"0","unit":"px"}};var bottomSQQyeN = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-SQQyeN layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":66.66,"Mobile":null},"elementId":"guten-yV9d02","verticalAlign":{"Desktop":"center"},"margin":{"Mobile":{}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"animation":{"type":{"Desktop":"none"}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-yV9d02"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="yV9d02"><script>var topyV9d02 = {"Desktop":{"point":"0","unit":"px"}};var bottomyV9d02 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-NY9Zk4","type":4,"textAlign":{"Mobile":"center"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"400","lineHeight":{"Tablet":{"point":"36","unit":"px"},"Mobile":{"point":"36","unit":"px"}}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
			<h4 class="wp-block-gutenverse-heading guten-element guten-NY9Zk4 animated guten-element-hide desktop-fadeInLeft">Needs Experience Business Consultant?</h4>
			<!-- /wp:gutenverse/heading --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-l4mXIp","verticalAlign":{"Desktop":"center"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-l4mXIp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="l4mXIp"><script>var topl4mXIp = {"Desktop":{"point":"0","unit":"px"}};var bottoml4mXIp = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-iKmyyU","content":"Contact Us","alignButton":{"Desktop":"right","Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}},"Tablet":{},"Mobile":{}},"buttonBackground":{"type":"default","color":{"r":100,"g":90,"b":255,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":78,"g":69,"b":217,"a":1}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"showIcon":true,"icon":"far fa-envelope","iconSpacing":{"Desktop":"14"},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"},"color":{"r":255,"g":255,"b":255,"a":1},"iconColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"14","unit":"px"}},"spacing":{"Desktop":"0.0625"},"transform":"uppercase"}} -->
			<div class="guten-element guten-button-wrapper guten-iKmyyU"><a class="guten-button animated guten-element-hide desktop-fadeInRight guten-button-sm" href="#"><i class="fa-lg far fa-envelope"></i><span>Contact Us</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
