<?php
/**
 * Gutenverse Services Section 2 content.
 */
return array(
	'title'      => __( 'Gutenverse Services Section 2', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-emxI51","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"50","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"20","left":"20"}}}} -->
			<div class="section-wrapper" data-id="emxI51"><script>var topemxI51 = {"Desktop":{"point":"0","unit":"px"}};var bottomemxI51 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-emxI51 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":null,"Mobile":null},"elementId":"guten-NZz0vS","margin":{"Desktop":{"unit":"px","dimension":{"right":"40"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-NZz0vS"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="NZz0vS"><script>var topNZz0vS = {"Desktop":{"point":"0","unit":"px"}};var bottomNZz0vS = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-jRzePZ","textAlign":{"Mobile":"center"},"color":{"r":18,"g":18,"b":34,"a":1},"typography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.15"},"Tablet":{"point":"36.8","unit":"px"},"Mobile":{"unit":"em","point":"1.15"}},"transform":"uppercase","spacing":{"Desktop":"0.094"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-jRzePZ animated guten-element-hide desktop-fadeInLeft">Years of Experience</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-JC9xca","alignment":{"Mobile":"center"},"textColor":{"r":102,"g":102,"b":102,"a":1},"typography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"},"Mobile":{"point":"13","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"},"Mobile":{"unit":"em","point":"1.7"}}},"margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
			<div class="guten-element gutenverse-text-editor guten-JC9xca animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ut labore et dolore magna aliqua. exercitation ullamco.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":null,"Mobile":null},"elementId":"guten-1Sz8S3","margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-1Sz8S3"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="1Sz8S3"><script>var top1Sz8S3 = {"Desktop":{"point":"0","unit":"px"}};var bottom1Sz8S3 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-pXuUxn","title":"Outstanding Service","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus.leo.","icon":"gtn gtn-medal","iconSize":{"Desktop":"50","Tablet":"40"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{}},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":{}},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"0","top":"0","bottom":"0"}}},"iconColor":{"r":78,"g":69,"b":217,"a":1},"iconHoverColor":{"r":78,"g":69,"b":217,"a":1},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"10"}}},"titleColor":{"r":18,"g":18,"b":34,"a":1},"titleHoverColor":{"r":18,"g":18,"b":34,"a":1},"titleTypography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"20","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"28.8","unit":"px"}}},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"descColor":{"r":102,"g":102,"b":102,"a":1},"descHoverColor":{"r":102,"g":102,"b":102,"a":1},"descTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
			<div class="guten-element guten-pXuUxn animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-medal"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Outstanding Service</h2><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus.leo.</p></div></div></div>
			<!-- /wp:gutenverse/icon-box -->

			<!-- wp:gutenverse/icon-box {"elementId":"guten-99v4uI","title":"Business Consultant","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus.leo.","icon":"gtn gtn-consut2-light","iconSize":{"Desktop":"50","Tablet":"40"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{},"Tablet":{}},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":{}},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"0","top":"0","bottom":"0"}}},"iconColor":{"r":78,"g":69,"b":217,"a":1},"iconHoverColor":{"r":78,"g":69,"b":217,"a":1},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"10"}},"Mobile":{}},"titleColor":{"r":18,"g":18,"b":34,"a":1},"titleHoverColor":{"r":18,"g":18,"b":34,"a":1},"titleTypography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"20","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"28.8","unit":"px"}}},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"descColor":{"r":102,"g":102,"b":102,"a":1},"descHoverColor":{"r":102,"g":102,"b":102,"a":1},"descTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"800"}} -->
			<div class="guten-element guten-99v4uI animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-consut2-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Business Consultant</h2><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus.leo.</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Mobile":null},"elementId":"guten-EMneBY","margin":{"Desktop":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-EMneBY"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="EMneBY"><script>var topEMneBY = {"Desktop":{"point":"0","unit":"px"}};var bottomEMneBY = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-eSYCJK","title":"Dedication to Clients","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus.leo.","icon":"gtn gtn-review-light","iconSize":{"Desktop":"50","Tablet":"40"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{}},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":{}},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"0","top":"0","bottom":"0"}}},"iconColor":{"r":78,"g":69,"b":217,"a":1},"iconHoverColor":{"r":78,"g":69,"b":217,"a":1},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"10"}}},"titleColor":{"r":18,"g":18,"b":34,"a":1},"titleHoverColor":{"r":18,"g":18,"b":34,"a":1},"titleTypography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"20","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"28.8","unit":"px"}}},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"descColor":{"r":102,"g":102,"b":102,"a":1},"descHoverColor":{"r":102,"g":102,"b":102,"a":1},"descTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
			<div class="guten-element guten-eSYCJK animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-review-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Dedication to Clients</h2><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus.leo.</p></div></div></div>
			<!-- /wp:gutenverse/icon-box -->

			<!-- wp:gutenverse/icon-box {"elementId":"guten-tJhKfs","title":"Professional Liability","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus.leo.","icon":"gtn gtn-team1-light","iconSize":{"Desktop":"50","Tablet":"40"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{},"Tablet":{}},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":{}},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"0","top":"0","bottom":"0"}}},"iconColor":{"r":78,"g":69,"b":217,"a":1},"iconHoverColor":{"r":78,"g":69,"b":217,"a":1},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"10"}}},"titleColor":{"r":18,"g":18,"b":34,"a":1},"titleHoverColor":{"r":18,"g":18,"b":34,"a":1},"titleTypography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"20","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"28.8","unit":"px"}}},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"descColor":{"r":102,"g":102,"b":102,"a":1},"descHoverColor":{"r":102,"g":102,"b":102,"a":1},"descTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"1000"}} -->
			<div class="guten-element guten-tJhKfs animated guten-element-hide desktop-fadeInUp guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-team1-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Professional Liability</h2><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus.leo.</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
