<?php
/**
 * Gutenverse Services Section 6 content.
 */
return array(
	'title'      => __( 'Gutenverse Services Section 6', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-eOtjK8","background":{"type":"default","color":{"r":25,"g":24,"b":47,"a":1}},"margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"20","left":"20"}}}} -->
			<div class="section-wrapper" data-id="eOtjK8"><script>var topeOtjK8 = {"Desktop":{"point":"0","unit":"px"}};var bottomeOtjK8 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-eOtjK8 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-SOG3qa"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-SOG3qa"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="SOG3qa"><script>var topSOG3qa = {"Desktop":{"point":"0","unit":"px"}};var bottomSOG3qa = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-jRo3C5","textAlign":{"Desktop":"center"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"32","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"48","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.094"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-jRo3C5 animated guten-element-hide desktop-fadeInUp">Contact info</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-vRQuba","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{},"Mobile":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
			<div class="section-wrapper" data-id="vRQuba"><script>var topvRQuba = {"Desktop":{"point":"0","unit":"px"}};var bottomvRQuba = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-vRQuba animated guten-element-hide desktop-fadeInUp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":null},"elementId":"guten-7LEF4R","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center"},"margin":{"Tablet":{},"Mobile":{}},"padding":{"Tablet":{"unit":"px","dimension":{"left":""}},"Mobile":{"unit":"px","dimension":{"left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-7LEF4R"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="7LEF4R"><script>var top7LEF4R = {"Desktop":{"point":"0","unit":"px"}};var bottom7LEF4R = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-list {"elementId":"guten-9wL4A1","alignList":{"Desktop":"flex-start"},"iconColor":{"r":78,"g":69,"b":217,"a":1},"iconColorHover":{"r":78,"g":69,"b":217,"a":1},"iconSize":{"Desktop":"18"},"textColor":{"r":255,"g":255,"b":255,"a":1},"textColorHover":{"r":255,"g":255,"b":255,"a":1},"textIndent":{"Desktop":"10"},"textTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"21","unit":"px"}}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}},"Desktop":{}},"padding":{"Mobile":{"unit":"px","dimension":{"left":"0"}},"Desktop":{"unit":"px","dimension":{"left":"30"}}}} -->
			<div class="guten-element guten-icon-list guten-9wL4A1"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-j5smtT"} -->
			<div class="guten-element guten-icon-list-item guten-j5smtT"><a id="guten-j5smtT"><i class="fas fa-map-pin"></i><span class="list-text ">1010 Avenue of the Moon New York, NY 10018 US.</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.33},"elementId":"guten-bNgCYr","verticalAlign":{"Desktop":"center"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-bNgCYr"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="bNgCYr"><script>var topbNgCYr = {"Desktop":{"point":"0","unit":"px"}};var bottombNgCYr = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-list {"elementId":"guten-HDtkif","alignList":{"Desktop":"center","Mobile":"flex-start"},"iconColor":{"r":78,"g":69,"b":217,"a":1},"iconColorHover":{"r":78,"g":69,"b":217,"a":1},"iconSize":{"Desktop":"18"},"textColor":{"r":255,"g":255,"b":255,"a":1},"textColorHover":{"r":255,"g":255,"b":255,"a":1},"textIndent":{"Desktop":"10"},"textTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"lineHeight":{"Desktop":{"point":"21","unit":"px"}},"weight":"400"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Mobile":{}}} -->
			<div class="guten-element guten-icon-list guten-HDtkif"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-4don3w"} -->
			<div class="guten-element guten-icon-list-item guten-4don3w"><a id="guten-4don3w"><i class="fas fa-phone-alt"></i><span class="list-text ">+1 628 123 4000</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":null},"elementId":"guten-3AYigz","verticalAlign":{"Desktop":"center"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-3AYigz"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="3AYigz"><script>var top3AYigz = {"Desktop":{"point":"0","unit":"px"}};var bottom3AYigz = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-list {"elementId":"guten-DRkVXm","alignList":{"Desktop":"center","Mobile":"flex-start"},"iconColor":{"r":78,"g":69,"b":217,"a":1},"iconColorHover":{"r":78,"g":69,"b":217,"a":1},"iconSize":{"Desktop":"18"},"textColor":{"r":255,"g":255,"b":255,"a":1},"textColorHover":{"r":255,"g":255,"b":255,"a":1},"textIndent":{"Desktop":"10"},"textTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"21","unit":"px"}}}} -->
			<div class="guten-element guten-icon-list guten-DRkVXm"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-Yk3wcN"} -->
			<div class="guten-element guten-icon-list-item guten-Yk3wcN"><a id="guten-Yk3wcN"><i class="fas fa-envelope"></i><span class="list-text ">contact@yourdomain.com</span></a></div>
			<!-- /wp:gutenverse/icon-list-item --></div>
			<!-- /wp:gutenverse/icon-list --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/google-maps {"elementId":"guten-K7O785","height":{"Mobile":"300"},"mapFilter":{"saturation":"0","hue":"360","contrast":"96"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
			<div class="guten-element gutenverse-maps guten-K7O785 animated guten-element-hide desktop-fadeInUp"><iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?q=New%20York&amp;z=13&amp;t=m&amp;output=embed&amp;iwloc=near" title="New York"></iframe></div>
			<!-- /wp:gutenverse/google-maps --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
