<?php
/**
 * Gutenverse Home Section 2 content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 2', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-zUeupM","margin":{"Desktop":{},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"200","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"150","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"120","bottom":"30","right":"","left":""}}}} -->
			<div class="section-wrapper" data-id="zUeupM"><script>var topzUeupM = {"Desktop":{"point":"0","unit":"px"}};var bottomzUeupM = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-zUeupM layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-zAeHg7"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-zAeHg7"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="zAeHg7"><script>var topzAeHg7 = {"Desktop":{"point":"0","unit":"px"}};var bottomzAeHg7 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-fj1JAq","textAlign":{"Desktop":"center"},"color":{"r":25,"g":24,"b":47,"a":1},"typography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"44","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"},"Tablet":{"point":"41.6","unit":"px"},"Mobile":{"point":"33.8","unit":"px"}},"weight":"400","transform":"uppercase","spacing":{"Desktop":"0.0625"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{}},"padding":{"Desktop":{},"Tablet":{}},"animation":{"type":{"Desktop":"slideInUp"},"duration":"normal","delay":"100"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-fj1JAq animated guten-element-hide desktop-slideInUp">We Provide Best Services</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-oswNC3","alignment":{"Desktop":"center"},"textColor":{"r":102,"g":102,"b":102,"a":1},"typography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"},"Mobile":{"point":"13","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"},"Tablet":{"point":"22.4","unit":"px"},"Mobile":{"point":"22.1","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"18","left":"18"}},"Tablet":{"unit":"%","dimension":{"right":"8","left":"8"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
			<div class="guten-element gutenverse-text-editor guten-oswNC3 animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris </p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-J7ShRg","margin":{"Desktop":{"unit":"px","dimension":{"top":"50"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
			<div class="section-wrapper" data-id="J7ShRg"><script>var topJ7ShRg = {"Desktop":{"point":"0","unit":"px"}};var bottomJ7ShRg = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-J7ShRg layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":25,"Mobile":null},"elementId":"guten-eL2X8c","margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"0"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"right":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-eL2X8c animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="eL2X8c"><script>var topeL2X8c = {"Desktop":{"point":"0","unit":"px"}};var bottomeL2X8c = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-bs5El7","title":"Business Strategy","description":"","icon":"gtn gtn-light-bulb-1-light","iconSize":{"Desktop":40,"Tablet":"32"},"iconPosition":"left","align":{"Desktop":"flex-start","Mobile":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"10","left":"15"}}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"10","left":"15"}},"Mobile":{}},"containerBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"all":{"type":"solid","width":"1","color":{"r":230,"g":230,"b":230,"a":1}}},"containerBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"r":230,"g":230,"b":230,"a":1}}},"containerBoxShadowHover":{"vertical":"4","blur":"16","color":{"r":0,"g":0,"b":0,"a":0.2},"position":"outline"},"iconPadding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"15"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"iconStyleMode":"color","iconColor":{"r":100,"g":90,"b":255,"a":1},"iconHoverColor":{"r":100,"g":90,"b":255,"a":1},"iconBorder":{"radius":{"Desktop":{},"Tablet":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"titleColor":{"r":25,"g":24,"b":47,"a":1},"titleHoverColor":{"r":25,"g":24,"b":47,"a":1},"titleTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"12","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"point":"21","unit":"px"}},"transform":"uppercase"},"descMargin":{"Desktop":{},"Tablet":{},"Mobile":{}}} -->
			<div class="guten-element guten-bs5El7 guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-light-bulb-1-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Business Strategy</h2><p class="icon-box-description"></p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":25,"Mobile":null},"elementId":"guten-EGc6Xo","margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-EGc6Xo animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="EGc6Xo"><script>var topEGc6Xo = {"Desktop":{"point":"0","unit":"px"}};var bottomEGc6Xo = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-8IBftd","title":"Tax Consulting","description":"","icon":"gtn gtn-Consultancy-light","iconSize":{"Desktop":40,"Tablet":"32"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"10","left":"15"}}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"10","left":"15"}}},"containerBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"all":{"type":"solid","width":"1","color":{"r":230,"g":230,"b":230,"a":1}}},"containerBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"all":{"type":"solid","width":"1","color":{"r":230,"g":230,"b":230,"a":1}}},"containerBoxShadowHover":{"vertical":"4","blur":"16","color":{"r":0,"g":0,"b":0,"a":0.2}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"15"}}},"iconStyleMode":"color","iconColor":{"r":100,"g":90,"b":255,"a":1},"iconHoverColor":{"r":100,"g":90,"b":255,"a":1},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"titleColor":{"r":25,"g":24,"b":47,"a":1},"titleHoverColor":{"r":25,"g":24,"b":47,"a":1},"titleTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"point":"21","unit":"px"}},"transform":"uppercase"},"descMargin":{"Desktop":{},"Tablet":{},"Mobile":{}}} -->
			<div class="guten-element guten-8IBftd guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-Consultancy-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Tax Consulting</h2><p class="icon-box-description"></p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":25,"Mobile":null},"elementId":"guten-1BoexJ","margin":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"bottom":"20","right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"700"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-1BoexJ animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="1BoexJ"><script>var top1BoexJ = {"Desktop":{"point":"0","unit":"px"}};var bottom1BoexJ = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-b6tDfk","title":"Customer Experience","description":"","icon":"gtn gtn-customer-support-2-light","iconSize":{"Desktop":40,"Tablet":"32"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"10","left":"15"}}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"10","left":"15"}},"Mobile":{}},"containerBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"all":{"type":"solid","width":"1","color":{"r":230,"g":230,"b":230,"a":1}}},"containerBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"type":"solid","width":"1","color":{"r":230,"g":230,"b":230,"a":1}}},"containerBoxShadowHover":{"vertical":"4","blur":"16","color":{"r":0,"g":0,"b":0,"a":0.2}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"15"}}},"iconStyleMode":"color","iconColor":{"r":100,"g":90,"b":255,"a":1},"iconHoverColor":{"r":100,"g":90,"b":255,"a":1},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Tablet":{"unit":"px","dimension":{"left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"titleColor":{"r":25,"g":24,"b":47,"a":1},"titleHoverColor":{"r":25,"g":24,"b":47,"a":1},"titleTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"point":"21","unit":"px"}},"transform":"uppercase"},"descMargin":{"Desktop":{},"Tablet":{},"Mobile":{}}} -->
			<div class="guten-element guten-b6tDfk guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-customer-support-2-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Customer Experience</h2><p class="icon-box-description"></p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":25,"Mobile":null},"elementId":"guten-cqqKNF","margin":{"Desktop":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"800"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-cqqKNF animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="cqqKNF"><script>var topcqqKNF = {"Desktop":{"point":"0","unit":"px"}};var bottomcqqKNF = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-clHHHq","title":"Financial Planning","description":"","icon":"gtn gtn-save-money-light","iconSize":{"Desktop":40,"Tablet":"32"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"10","left":"15"}}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"10","left":"15"}}},"containerBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"all":{"type":"solid","width":"1","color":{"r":230,"g":230,"b":230,"a":1}}},"containerBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{}},"all":{"type":"solid","width":"1","color":{"r":230,"g":230,"b":230,"a":1}}},"containerBoxShadowHover":{"vertical":"4","blur":"16","color":{"r":0,"g":0,"b":0,"a":0.2}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"15"}}},"iconStyleMode":"color","iconColor":{"r":100,"g":90,"b":255,"a":1},"iconHoverColor":{"r":100,"g":90,"b":255,"a":1},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":{},"Mobile":{}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Tablet":{"unit":"px","dimension":{"right":"","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"titleColor":{"r":25,"g":24,"b":47,"a":1},"titleHoverColor":{"r":25,"g":24,"b":47,"a":1},"titleTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"point":"21","unit":"px"}},"transform":"uppercase"},"descMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
			<div class="guten-element guten-clHHHq guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-save-money-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Financial Planning</h2><p class="icon-box-description"></p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
