<?php
/**
 * Gutenverse About Section 2 content.
 */
return array(
	'title'      => __( 'Gutenverse About Section 2', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1170"},"gap":"no","elementId":"guten-RBhphY","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
			<div class="section-wrapper" data-id="RBhphY"><script>var topRBhphY = {"Desktop":{"point":"0","unit":"px"}};var bottomRBhphY = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-RBhphY layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25},"elementId":"guten-dsJN5g","border":{"radius":{"Desktop":{}},"right":{"type":"solid","width":"1","color":{"r":230,"g":230,"b":230,"a":1}},"top":{"type":"solid","width":"1","color":{"r":230,"g":230,"b":230,"a":1}},"bottom":{"type":"solid","width":"1","color":{"r":230,"g":230,"b":230,"a":1}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-dsJN5g animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="dsJN5g"><script>var topdsJN5g = {"Desktop":{"point":"0","unit":"px"}};var bottomdsJN5g = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-WmWWNP","title":"Expericence","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et eiusmod tempor dolore magna aliqua. ","icon":"gtn gtn-Rating-light","iconSize":{"Desktop":"50","Tablet":"50"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"50","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"30","bottom":"30","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"30","bottom":"30","right":"20","left":"20"}}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"50","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"30","bottom":"30","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"20"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"type":"none","width":"","color":""}},"containerBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{}},"iconStyleMode":"color","iconColor":{"r":100,"g":90,"b":255,"a":1},"iconHoverColor":{"r":100,"g":90,"b":255,"a":1},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":""}},"Mobile":{}},"titleMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"titleColor":{"r":18,"g":18,"b":34,"a":1},"titleHoverColor":{"r":18,"g":18,"b":34,"a":1},"titleTypography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"18","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"28.8","unit":"px"},"Tablet":{"point":"21.6","unit":"px"}}},"descMargin":{"Desktop":{},"Tablet":{},"Mobile":{}},"descColor":{"r":102,"g":102,"b":102,"a":1},"descHoverColor":{"r":102,"g":102,"b":102,"a":1},"descTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"},"Mobile":{"point":"13","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"},"Tablet":{"point":"22.1","unit":"px"}}},"margin":{"Mobile":{}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
			<div class="guten-element guten-WmWWNP guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-Rating-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Expericence</h2><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et eiusmod tempor dolore magna aliqua. </p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":25},"elementId":"guten-nUmYDQ","border":{"radius":{"Desktop":{}},"right":{"type":"solid","width":"1","color":{"r":230,"g":230,"b":230,"a":1}},"top":{"type":"solid","width":"1","color":{"r":230,"g":230,"b":230,"a":1}},"bottom":{"type":"solid","width":"1","color":{"r":230,"g":230,"b":230,"a":1}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-nUmYDQ animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="nUmYDQ"><script>var topnUmYDQ = {"Desktop":{"point":"0","unit":"px"}};var bottomnUmYDQ = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-O6H1rE","title":"Services","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et eiusmod tempor dolore magna aliqua. ","icon":"gtn gtn-consut2-light","iconSize":{"Desktop":"50","Tablet":"50"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"50","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"30","bottom":"30","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"20"}}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"50","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"30","bottom":"30","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"20"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"type":"none","width":"","color":{"r":230,"g":230,"b":230,"a":1}},"top":{"type":"none","width":"","color":""}},"containerBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"type":"none","width":"","color":""}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{}},"iconStyleMode":"color","iconColor":{"r":100,"g":90,"b":255,"a":1},"iconHoverColor":{"r":100,"g":90,"b":255,"a":1},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":{}},"titleMargin":{"Desktop":{},"Tablet":{}},"titleColor":{"r":18,"g":18,"b":34,"a":1},"titleHoverColor":{"r":18,"g":18,"b":34,"a":1},"titleTypography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"18","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"28.8","unit":"px"},"Tablet":{"point":"21.6","unit":"px"}}},"descMargin":{"Desktop":{},"Tablet":{}},"descColor":{"r":102,"g":102,"b":102,"a":1},"descHoverColor":{"r":102,"g":102,"b":102,"a":1},"descTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"},"Tablet":{"point":"22.1","unit":"px"}}}} -->
			<div class="guten-element guten-O6H1rE guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-consut2-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Services</h2><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et eiusmod tempor dolore magna aliqua. </p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":25},"elementId":"guten-GDs4bm","border":{"radius":{"Desktop":{}},"right":{"type":"solid","width":"1","color":{"r":230,"g":230,"b":230,"a":1}},"top":{"type":"solid","width":"1","color":{"r":230,"g":230,"b":230,"a":1}},"bottom":{"type":"solid","width":"1","color":{"r":230,"g":230,"b":230,"a":1}}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-GDs4bm animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="GDs4bm"><script>var topGDs4bm = {"Desktop":{"point":"0","unit":"px"}};var bottomGDs4bm = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-S2e8ds","title":"Team","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et eiusmod tempor dolore magna aliqua. ","icon":"gtn gtn-team-1-light","iconSize":{"Desktop":"50","Tablet":"50"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"50","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"30","bottom":"30","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"20"}}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"50","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"30","bottom":"30","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"20"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"type":"none","width":"","color":{"r":230,"g":230,"b":230,"a":1}},"top":{"type":"none","width":"","color":""}},"containerBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"type":"none","width":"","color":""}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{}},"iconStyleMode":"color","iconColor":{"r":100,"g":90,"b":255,"a":1},"iconHoverColor":{"r":100,"g":90,"b":255,"a":1},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":{}},"titleMargin":{"Desktop":{},"Tablet":{}},"titleColor":{"r":18,"g":18,"b":34,"a":1},"titleHoverColor":{"r":18,"g":18,"b":34,"a":1},"titleTypography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"18","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"28.8","unit":"px"},"Tablet":{"point":"21.6","unit":"px"}}},"descMargin":{"Desktop":{},"Tablet":{}},"descColor":{"r":102,"g":102,"b":102,"a":1},"descHoverColor":{"r":102,"g":102,"b":102,"a":1},"descTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"},"Tablet":{"point":"22.1","unit":"px"}}}} -->
			<div class="guten-element guten-S2e8ds guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-team-1-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Team</h2><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et eiusmod tempor dolore magna aliqua. </p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":25},"elementId":"guten-Uccfk7","border":{"radius":{"Desktop":{}},"top":{"type":"solid","width":"1","color":{"r":230,"g":230,"b":230,"a":1}},"bottom":{"type":"solid","width":"1","color":{"r":230,"g":230,"b":230,"a":1}},"right":{"type":"solid","width":"1","color":{"r":230,"g":230,"b":230,"a":1}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"800"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-Uccfk7 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Uccfk7"><script>var topUccfk7 = {"Desktop":{"point":"0","unit":"px"}};var bottomUccfk7 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-HoVBXj","title":"Budget","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et eiusmod tempor dolore magna aliqua. ","icon":"gtn gtn-money-3-light","iconSize":{"Desktop":"50","Tablet":"50"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"50","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"20"}}},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"50","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"20"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"type":"none","width":"","color":""}},"containerBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{},"Mobile":{}},"all":{"type":"none","width":"","color":""}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{}},"iconStyleMode":"color","iconColor":{"r":100,"g":90,"b":255,"a":1},"iconHoverColor":{"r":100,"g":90,"b":255,"a":1},"iconBorder":{"radius":{"Desktop":{}}},"iconBorderHover":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":{},"Tablet":{}},"titleMargin":{"Desktop":{},"Tablet":{}},"titleColor":{"r":18,"g":18,"b":34,"a":1},"titleHoverColor":{"r":18,"g":18,"b":34,"a":1},"titleTypography":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"18","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"point":"28.8","unit":"px"},"Tablet":{"point":"21.6","unit":"px"}}},"descMargin":{"Desktop":{},"Tablet":{}},"descColor":{"r":102,"g":102,"b":102,"a":1},"descHoverColor":{"r":102,"g":102,"b":102,"a":1},"descTypography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"13","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"},"Tablet":{"point":"22.1","unit":"px"}}}} -->
			<div class="guten-element guten-HoVBXj guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-money-3-light"></i></div></div><div class="icon-box icon-box-body"><h2 class="title">Budget</h2><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et eiusmod tempor dolore magna aliqua. </p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
