<?php
/**
 * Gutenverse Single Post Section 2 content.
 */
return array(
	'title'      => __( 'Gutenverse Single Post Section 2', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"800","Tablet":"720"},"gap":"no","elementId":"guten-G4pEwx","margin":{"Desktop":{"unit":"px","dimension":{"top":"40","bottom":"100"}},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","left":"0"}}}} -->
			<div class="section-wrapper" data-id="G4pEwx"><script>var topG4pEwx = {"Desktop":{"point":"0","unit":"px"}};var bottomG4pEwx = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-G4pEwx layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-J7j3QA"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-J7j3QA"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="J7j3QA"><script>var topJ7j3QA = {"Desktop":{"point":"0","unit":"px"}};var bottomJ7j3QA = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/post-content {"elementId":"guten-4ghlQv","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}}},"padding":{"Desktop":{},"Mobile":{}}} -->
			<div class="guten-element guten-post-content guten-4ghlQv"></div>
			<!-- /wp:gutenverse/post-content -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-ZY2u2P","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Desktop":{}}} -->
			<div class="section-wrapper" data-id="ZY2u2P"><script>var topZY2u2P = {"Desktop":{"point":"0","unit":"px"}};var bottomZY2u2P = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-ZY2u2P layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-WKPvnA","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-WKPvnA"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="WKPvnA"><script>var topWKPvnA = {"Desktop":{"point":"0","unit":"px"}};var bottomWKPvnA = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-ducD8X","textAlign":{"Desktop":"center"},"color":{"r":0,"g":0,"b":0,"a":1},"typography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"}},"weight":"600","transform":"uppercase","lineHeight":{"Desktop":{"point":"14","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Desktop":{}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-ducD8X">Share this post</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/social-share {"elementId":"guten-d5TyFD","iconPading":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"textPading":{"Desktop":{}},"borderType":{"radius":{"Desktop":{},"Mobile":{}}},"iconSize":{"Desktop":{"point":"14","unit":"px"}},"typography":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"13","unit":"px"}},"weight":"500","lineHeight":{"Desktop":{"point":"19","unit":"px"}},"transform":"uppercase","spacing":{"Desktop":"0.063"}},"gap":{"Desktop":"10"}} -->
			<div class="guten-element guten-social-share guten-d5TyFD guten-social-share"><!-- wp:gutenverse/social-share-facebook {"elementId":"guten-KqCfQj","iconPading":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"20"}}},"textPading":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"20","bottom":"10","left":"0"}}},"iconColor":{"r":255,"g":255,"b":255,"a":1},"iconBackgroundColor":{"r":59,"g":89,"b":152,"a":1},"backgroundColor":{"r":59,"g":89,"b":152,"a":1},"textColor":{"r":255,"g":255,"b":255,"a":1},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"iconColorHover":{"r":255,"g":255,"b":255,"a":1},"iconBackgroundColorHover":{"r":10,"g":100,"b":188,"a":1},"backgroundColorHover":{"r":10,"g":100,"b":188,"a":1},"textColorHover":{"r":255,"g":255,"b":255,"a":1},"borderHover":{"radius":{"Desktop":{}}},"text":"Facebook"} /-->

			<!-- wp:gutenverse/social-share-twitter {"elementId":"guten-2kk9lB","iconPading":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"20"}}},"textPading":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"20","bottom":"10","left":"0"}}},"iconColor":{"r":255,"g":255,"b":255,"a":1},"iconBackgroundColor":{"r":0,"g":172,"b":238,"a":1},"backgroundColor":{"r":0,"g":172,"b":238,"a":1},"textColor":{"r":255,"g":255,"b":255,"a":1},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"iconColorHover":{"r":255,"g":255,"b":255,"a":1},"iconBackgroundColorHover":{"r":0,"g":185,"b":255,"a":1},"backgroundColorHover":{"r":0,"g":185,"b":255,"a":1},"textColorHover":{"r":255,"g":255,"b":255,"a":1},"borderHover":{"radius":{"Desktop":{}}},"text":"Twitter"} /-->

			<!-- wp:gutenverse/social-share-linkedin {"elementId":"guten-gc9aCQ","iconPading":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"20"}}},"textPading":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"20","bottom":"10","left":"0"}}},"iconColor":{"r":255,"g":255,"b":255,"a":1},"iconBackgroundColor":{"r":0,"g":119,"b":181,"a":1},"backgroundColor":{"r":0,"g":119,"b":181,"a":1},"textColor":{"r":255,"g":255,"b":255,"a":1},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"iconColorHover":{"r":255,"g":255,"b":255,"a":1},"iconBackgroundColorHover":{"r":0,"g":160,"b":220,"a":1},"backgroundColorHover":{"r":0,"g":160,"b":220,"a":1},"textColorHover":{"r":255,"g":255,"b":255,"a":1},"borderHover":{"radius":{"Desktop":{}}},"text":"Linkedin"} /-->

			<!-- wp:gutenverse/social-share-whatsapp {"elementId":"guten-xkQyO6","iconPading":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"20"}}},"textPading":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"20","bottom":"10","left":"0"}}},"iconColor":{"r":255,"g":255,"b":255,"a":1},"iconBackgroundColor":{"r":23,"g":167,"b":77,"a":1},"backgroundColor":{"r":23,"g":167,"b":77,"a":1},"textColor":{"r":255,"g":255,"b":255,"a":1},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"text":"Whatsapp"} /--></div>
			<!-- /wp:gutenverse/social-share --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/post-comment {"elementId":"guten-XbWBEP","typographyHeading":{"font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"point":"28","unit":"px"}},"lineHeight":{"Desktop":{"point":"40","unit":"px"}},"weight":"800"},"typographyText":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"30","unit":"px"}},"weight":"400"},"typographyLink":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"22.5","unit":"px"}},"weight":"400"},"typographyLabel":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"40","unit":"px"}},"weight":"400"},"colorHeading":{"r":18,"g":18,"b":34,"a":1},"colorText":{"r":18,"g":18,"b":34,"a":1},"colorLink":{"r":100,"g":90,"b":255,"a":1},"colorLabel":{"r":18,"g":18,"b":34,"a":1},"inputBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"r":234,"g":234,"b":239,"a":1}}},"typographyButton":{"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"point":"28","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.0625"}},"colorButton":{"r":255,"g":255,"b":255,"a":1},"bgcolorButton":{"r":100,"g":90,"b":255,"a":1},"borderButton":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"colorButtonHover":{"r":255,"g":255,"b":255,"a":1},"bgcolorButtonHover":{"r":78,"g":69,"b":217,"a":1},"borderButtonHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{}},"padding":{"Desktop":{}}} -->
			<div class="guten-element guten-post-comment guten-XbWBEP"></div>
			<!-- /wp:gutenverse/post-comment --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
